services:
  - type: web
    name: lookrooms-bot
    env: python
    pythonVersion: 3.11        # <== вот эта строка ключевая!
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: API_TOKEN
        value: 8404119240:AAHvfgS8vh4j3OkTr73dLnFUUzYAcBSAw6E
      - key: GOOGLE_SHEET_ID
        value: 1k9LnA_IShTjFzsmRdtFwjbT_wEGZ5u0IM4g3CB5XYW0


